version: "3.9"

services:
  postgres:
    container_name: postgres-rust-project
    image: postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD=p4ssw0rd
      - POSTGRES_DB=rustProject
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - rust-project

volumes:
  postgresdata:
    name: rustprojectpostgresdata
    external: false

networks:
  rust-project:
    name: rust-project
    driver: bridge
