version: "3.9"

services:
  rabbitmq:
    container_name: rabbitmq-rust-project
    image: rabbitmq:3.12.6-management
    environment:
      - RABBITMQ_DEFAULT_USER=rust
      - RABBITMQ_DEFAULT_PASS=p4ssw0rd
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq/
    networks:
      - rust-project

  postgres:
    container_name: postgres-rust-project
    image: postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD=p4ssw0rd
      - POSTGRES_DB=rustProject
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - rust-project

volumes:
  postgresdata:
    name: rustprojectpostgresdata
    external: false
  rabbitmqdata:
    name: rustprojectrabbitmqdata
    external: false

networks:
  rust-project:
    name: rust-project
    driver: bridge
